# Use the official Rasa SDK image as a base
FROM rasa/rasa-sdk:latest

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Copy the actions folder to the Docker container
COPY actions /app/actions

# Set the working directory
WORKDIR /app

# Install dependencies if you have a requirements.txt file
COPY requirements.txt .
RUN pip install -r requirements.txt

# Expose the port
EXPOSE 5055

# Run the action server
CMD ["rasa", "run", "actions"]
